<?php
/**
 * FeedDataServiceSelector
 *
 * PHP version 7.2
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Yahoo!広告 ディスプレイ広告 API リファレンス / Yahoo! JAPAN Ads Display Ads API Reference
 *
 * <div lang=\"ja\">Yahoo!広告 ディスプレイ広告 APIのWebサービスについて説明します。</div> <div lang=\"en\">Display Ads API Web Services supported in Yahoo! JAPAN Ads API.</div> <div><a target=\"_blank\" href=\"https://github.com/yahoojp-marketing/ads-display-api-documents/blob/master/design/v4/Route.yaml\">OpenAPI Specification</a></div> <div lang=\"ja\"><a target=\"_blank\" href=\"https://github.com/yahoojp-marketing/ads-display-api-documents/blob/master/bestpractice/ja\">Best Practice</a></div> <div lang=\"en\"><a target=\"_blank\" href=\"https://github.com/yahoojp-marketing/ads-display-api-documents/blob/master/bestpractice/en\">Best Practice</a></div>
 *
 * The version of the OpenAPI document: v4
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.1.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;

use \ArrayAccess;
use \OpenAPI\Client\ObjectSerializer;

/**
 * FeedDataServiceSelector Class Doc Comment
 *
 * @category Class
 * @description &lt;div lang&#x3D;\&quot;ja\&quot;&gt;get操作の検索条件を保持するオブジェクト&lt;/div&gt; &lt;div lang&#x3D;\&quot;en\&quot;&gt;FeedDataServiceSelector object retains search condition of get operation.&lt;/div&gt;
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<TKey, TValue>
 * @template TKey int|null
 * @template TValue mixed|null  
 */
class FeedDataServiceSelector implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'FeedDataServiceSelector';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'account_id' => 'int',
        'feed_ids' => 'int[]',
        'file_upload_date_range' => '\OpenAPI\Client\Model\FeedDataServiceFileUploadDateRange',
        'item_list_upload_ids' => 'int[]',
        'number_results' => 'int',
        'start_index' => 'int',
        'upload_statuses' => '\OpenAPI\Client\Model\FeedDataServiceFileUploadStatus[]'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'account_id' => 'int64',
        'feed_ids' => 'int64',
        'file_upload_date_range' => null,
        'item_list_upload_ids' => 'int64',
        'number_results' => 'int32',
        'start_index' => 'int32',
        'upload_statuses' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'account_id' => 'accountId',
        'feed_ids' => 'feedIds',
        'file_upload_date_range' => 'fileUploadDateRange',
        'item_list_upload_ids' => 'itemListUploadIds',
        'number_results' => 'numberResults',
        'start_index' => 'startIndex',
        'upload_statuses' => 'uploadStatuses'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'account_id' => 'setAccountId',
        'feed_ids' => 'setFeedIds',
        'file_upload_date_range' => 'setFileUploadDateRange',
        'item_list_upload_ids' => 'setItemListUploadIds',
        'number_results' => 'setNumberResults',
        'start_index' => 'setStartIndex',
        'upload_statuses' => 'setUploadStatuses'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'account_id' => 'getAccountId',
        'feed_ids' => 'getFeedIds',
        'file_upload_date_range' => 'getFileUploadDateRange',
        'item_list_upload_ids' => 'getItemListUploadIds',
        'number_results' => 'getNumberResults',
        'start_index' => 'getStartIndex',
        'upload_statuses' => 'getUploadStatuses'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['account_id'] = $data['account_id'] ?? null;
        $this->container['feed_ids'] = $data['feed_ids'] ?? null;
        $this->container['file_upload_date_range'] = $data['file_upload_date_range'] ?? null;
        $this->container['item_list_upload_ids'] = $data['item_list_upload_ids'] ?? null;
        $this->container['number_results'] = $data['number_results'] ?? 20;
        $this->container['start_index'] = $data['start_index'] ?? 1;
        $this->container['upload_statuses'] = $data['upload_statuses'] ?? null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['account_id'] === null) {
            $invalidProperties[] = "'account_id' can't be null";
        }
        if (!is_null($this->container['feed_ids']) && (count($this->container['feed_ids']) > 200)) {
            $invalidProperties[] = "invalid value for 'feed_ids', number of items must be less than or equal to 200.";
        }

        if (!is_null($this->container['item_list_upload_ids']) && (count($this->container['item_list_upload_ids']) > 200)) {
            $invalidProperties[] = "invalid value for 'item_list_upload_ids', number of items must be less than or equal to 200.";
        }

        if (!is_null($this->container['number_results']) && ($this->container['number_results'] > 500)) {
            $invalidProperties[] = "invalid value for 'number_results', must be smaller than or equal to 500.";
        }

        if (!is_null($this->container['number_results']) && ($this->container['number_results'] < 1)) {
            $invalidProperties[] = "invalid value for 'number_results', must be bigger than or equal to 1.";
        }

        if (!is_null($this->container['start_index']) && ($this->container['start_index'] < 1)) {
            $invalidProperties[] = "invalid value for 'start_index', must be bigger than or equal to 1.";
        }

        if (!is_null($this->container['upload_statuses']) && (count($this->container['upload_statuses']) > 4)) {
            $invalidProperties[] = "invalid value for 'upload_statuses', number of items must be less than or equal to 4.";
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets account_id
     *
     * @return int
     */
    public function getAccountId()
    {
        return $this->container['account_id'];
    }

    /**
     * Sets account_id
     *
     * @param int $account_id <div lang=\"ja\">アカウントID</div> <div lang=\"en\">Account ID</div>
     *
     * @return self
     */
    public function setAccountId($account_id)
    {
        $this->container['account_id'] = $account_id;

        return $this;
    }

    /**
     * Gets feed_ids
     *
     * @return int[]|null
     */
    public function getFeedIds()
    {
        return $this->container['feed_ids'];
    }

    /**
     * Sets feed_ids
     *
     * @param int[]|null $feed_ids <div lang=\"ja\">フィードID</div> <div lang=\"en\">FeedID</div>
     *
     * @return self
     */
    public function setFeedIds($feed_ids)
    {

        if (!is_null($feed_ids) && (count($feed_ids) > 200)) {
            throw new \InvalidArgumentException('invalid value for $feed_ids when calling FeedDataServiceSelector., number of items must be less than or equal to 200.');
        }
        $this->container['feed_ids'] = $feed_ids;

        return $this;
    }

    /**
     * Gets file_upload_date_range
     *
     * @return \OpenAPI\Client\Model\FeedDataServiceFileUploadDateRange|null
     */
    public function getFileUploadDateRange()
    {
        return $this->container['file_upload_date_range'];
    }

    /**
     * Sets file_upload_date_range
     *
     * @param \OpenAPI\Client\Model\FeedDataServiceFileUploadDateRange|null $file_upload_date_range file_upload_date_range
     *
     * @return self
     */
    public function setFileUploadDateRange($file_upload_date_range)
    {
        $this->container['file_upload_date_range'] = $file_upload_date_range;

        return $this;
    }

    /**
     * Gets item_list_upload_ids
     *
     * @return int[]|null
     */
    public function getItemListUploadIds()
    {
        return $this->container['item_list_upload_ids'];
    }

    /**
     * Sets item_list_upload_ids
     *
     * @param int[]|null $item_list_upload_ids <div lang=\"ja\">アップロードした商品情報ID</div> <div lang=\"en\">Uploaded item list ID.</div>
     *
     * @return self
     */
    public function setItemListUploadIds($item_list_upload_ids)
    {

        if (!is_null($item_list_upload_ids) && (count($item_list_upload_ids) > 200)) {
            throw new \InvalidArgumentException('invalid value for $item_list_upload_ids when calling FeedDataServiceSelector., number of items must be less than or equal to 200.');
        }
        $this->container['item_list_upload_ids'] = $item_list_upload_ids;

        return $this;
    }

    /**
     * Gets number_results
     *
     * @return int|null
     */
    public function getNumberResults()
    {
        return $this->container['number_results'];
    }

    /**
     * Sets number_results
     *
     * @param int|null $number_results <div lang=\"ja\">ページの最大件数です。このフィールドは、1以上を指定する必要があります。</div> <div lang=\"en\">Maximum number of results to return in this page. This field must be greater than or equal to 1. Also see Entity Limits per operation.</div>
     *
     * @return self
     */
    public function setNumberResults($number_results)
    {

        if (!is_null($number_results) && ($number_results > 500)) {
            throw new \InvalidArgumentException('invalid value for $number_results when calling FeedDataServiceSelector., must be smaller than or equal to 500.');
        }
        if (!is_null($number_results) && ($number_results < 1)) {
            throw new \InvalidArgumentException('invalid value for $number_results when calling FeedDataServiceSelector., must be bigger than or equal to 1.');
        }

        $this->container['number_results'] = $number_results;

        return $this;
    }

    /**
     * Gets start_index
     *
     * @return int|null
     */
    public function getStartIndex()
    {
        return $this->container['start_index'];
    }

    /**
     * Sets start_index
     *
     * @param int|null $start_index <div lang=\"ja\">ページの先頭のインデックスです。このフィールドは、1以上を指定する必要があります。</div> <div lang=\"en\">Index of the first result to return in this page. This field must be greater than or equal to 1.</div>
     *
     * @return self
     */
    public function setStartIndex($start_index)
    {

        if (!is_null($start_index) && ($start_index < 1)) {
            throw new \InvalidArgumentException('invalid value for $start_index when calling FeedDataServiceSelector., must be bigger than or equal to 1.');
        }

        $this->container['start_index'] = $start_index;

        return $this;
    }

    /**
     * Gets upload_statuses
     *
     * @return \OpenAPI\Client\Model\FeedDataServiceFileUploadStatus[]|null
     */
    public function getUploadStatuses()
    {
        return $this->container['upload_statuses'];
    }

    /**
     * Sets upload_statuses
     *
     * @param \OpenAPI\Client\Model\FeedDataServiceFileUploadStatus[]|null $upload_statuses upload_statuses
     *
     * @return self
     */
    public function setUploadStatuses($upload_statuses)
    {

        if (!is_null($upload_statuses) && (count($upload_statuses) > 4)) {
            throw new \InvalidArgumentException('invalid value for $upload_statuses when calling FeedDataServiceSelector., number of items must be less than or equal to 4.');
        }
        $this->container['upload_statuses'] = $upload_statuses;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


