<?php
/**
 * GuaranteedReservation
 *
 * PHP version 7.2
 *
 * @category Class
 * @package  YahooAdsDisplayApi\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Yahoo!広告 ディスプレイ広告 API リファレンス / Yahoo! JAPAN Ads Display Ads API Reference
 *
 * <div lang=\"ja\">Yahoo!広告 ディスプレイ広告 APIのWebサービスについて説明します。</div> <div lang=\"en\">Display Ads API Web Services supported in Yahoo! JAPAN Ads API.</div> <div><a target=\"_blank\" href=\"https://github.com/yahoojp-marketing/ads-display-api-documents/blob/master/design/v4/Route.yaml\">OpenAPI Specification</a></div> <div lang=\"ja\"><a target=\"_blank\" href=\"https://github.com/yahoojp-marketing/ads-display-api-documents/blob/master/bestpractice/ja\">Best Practice</a></div> <div lang=\"en\"><a target=\"_blank\" href=\"https://github.com/yahoojp-marketing/ads-display-api-documents/blob/master/bestpractice/en\">Best Practice</a></div>
 *
 * The version of the OpenAPI document: v4
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.1.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace YahooAdsDisplayApi\Client\Model;

use \ArrayAccess;
use \YahooAdsDisplayApi\Client\ObjectSerializer;

/**
 * GuaranteedReservation Class Doc Comment
 *
 * @category Class
 * @description &lt;div lang&#x3D;\&quot;ja\&quot;&gt;GuaranteedReservationオブジェクトは、シミュレーション結果に基づいた予約情報を保持します。&lt;/div&gt; &lt;div lang&#x3D;\&quot;en\&quot;&gt;GuaranteedReservation object contains a reservation information based on simulation result. &lt;/div&gt;
 * @package  YahooAdsDisplayApi\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<TKey, TValue>
 * @template TKey int|null
 * @template TValue mixed|null  
 */
class GuaranteedReservation implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'GuaranteedReservation';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'account_id' => 'int',
        'guaranteed_simulation_id' => 'int',
        'lifetime_budget' => 'int',
        'ad_group_name' => 'string',
        'campaign_name' => 'string',
        'notification_email_address' => 'string[]'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'account_id' => 'int64',
        'guaranteed_simulation_id' => 'int64',
        'lifetime_budget' => 'int64',
        'ad_group_name' => null,
        'campaign_name' => null,
        'notification_email_address' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'account_id' => 'accountId',
        'guaranteed_simulation_id' => 'guaranteedSimulationId',
        'lifetime_budget' => 'lifetimeBudget',
        'ad_group_name' => 'adGroupName',
        'campaign_name' => 'campaignName',
        'notification_email_address' => 'notificationEmailAddress'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'account_id' => 'setAccountId',
        'guaranteed_simulation_id' => 'setGuaranteedSimulationId',
        'lifetime_budget' => 'setLifetimeBudget',
        'ad_group_name' => 'setAdGroupName',
        'campaign_name' => 'setCampaignName',
        'notification_email_address' => 'setNotificationEmailAddress'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'account_id' => 'getAccountId',
        'guaranteed_simulation_id' => 'getGuaranteedSimulationId',
        'lifetime_budget' => 'getLifetimeBudget',
        'ad_group_name' => 'getAdGroupName',
        'campaign_name' => 'getCampaignName',
        'notification_email_address' => 'getNotificationEmailAddress'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['account_id'] = $data['account_id'] ?? null;
        $this->container['guaranteed_simulation_id'] = $data['guaranteed_simulation_id'] ?? null;
        $this->container['lifetime_budget'] = $data['lifetime_budget'] ?? null;
        $this->container['ad_group_name'] = $data['ad_group_name'] ?? null;
        $this->container['campaign_name'] = $data['campaign_name'] ?? null;
        $this->container['notification_email_address'] = $data['notification_email_address'] ?? null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets account_id
     *
     * @return int|null
     */
    public function getAccountId()
    {
        return $this->container['account_id'];
    }

    /**
     * Sets account_id
     *
     * @param int|null $account_id <div lang=\"ja\"> アカウントIDです。<br> このフィールドは、リクエストの場合は必須です。 </div> <div lang=\"en\"> Account ID.<br> This field is required in requests. </div>
     *
     * @return self
     */
    public function setAccountId($account_id)
    {
        $this->container['account_id'] = $account_id;

        return $this;
    }

    /**
     * Gets guaranteed_simulation_id
     *
     * @return int|null
     */
    public function getGuaranteedSimulationId()
    {
        return $this->container['guaranteed_simulation_id'];
    }

    /**
     * Sets guaranteed_simulation_id
     *
     * @param int|null $guaranteed_simulation_id <div lang=\"ja\"> シミュレーションIDです。<br> このフィールドは、リクエストの場合は必須です。 </div> <div lang=\"en\"> Simulation ID. <br> This field is required in requests. </div>
     *
     * @return self
     */
    public function setGuaranteedSimulationId($guaranteed_simulation_id)
    {
        $this->container['guaranteed_simulation_id'] = $guaranteed_simulation_id;

        return $this;
    }

    /**
     * Gets lifetime_budget
     *
     * @return int|null
     */
    public function getLifetimeBudget()
    {
        return $this->container['lifetime_budget'];
    }

    /**
     * Sets lifetime_budget
     *
     * @param int|null $lifetime_budget <div lang=\"ja\"> キャンペーンの通期予算額です。<br> ※この「通期予算」は、キャンペーンの全期間を通じて消費される予算を意味します。<br> このフィールドは、リクエストの場合は必須です。 </div> <div lang=\"en\"> An amount of campaign's lifetime budget.<br> * \"lifetime budget\" means the total budget that is spent throughout the entire duration of the campaign.<br> This field is required in requests. </div>
     *
     * @return self
     */
    public function setLifetimeBudget($lifetime_budget)
    {
        $this->container['lifetime_budget'] = $lifetime_budget;

        return $this;
    }

    /**
     * Gets ad_group_name
     *
     * @return string|null
     */
    public function getAdGroupName()
    {
        return $this->container['ad_group_name'];
    }

    /**
     * Sets ad_group_name
     *
     * @param string|null $ad_group_name <div lang=\"ja\"> 広告グループ名です。<br> このフィールドは、リクエストの場合は必須です。 </div> <div lang=\"en\"> Ad group name.<br> This field is required in requests. </div>
     *
     * @return self
     */
    public function setAdGroupName($ad_group_name)
    {
        $this->container['ad_group_name'] = $ad_group_name;

        return $this;
    }

    /**
     * Gets campaign_name
     *
     * @return string|null
     */
    public function getCampaignName()
    {
        return $this->container['campaign_name'];
    }

    /**
     * Sets campaign_name
     *
     * @param string|null $campaign_name <div lang=\"ja\"> キャンペーン名です。<br> このフィールドは、リクエストの場合は必須です。 </div> <div lang=\"en\"> Campaign name.<br> This field is required in requests. </div>
     *
     * @return self
     */
    public function setCampaignName($campaign_name)
    {
        $this->container['campaign_name'] = $campaign_name;

        return $this;
    }

    /**
     * Gets notification_email_address
     *
     * @return string[]|null
     */
    public function getNotificationEmailAddress()
    {
        return $this->container['notification_email_address'];
    }

    /**
     * Sets notification_email_address
     *
     * @param string[]|null $notification_email_address <div lang=\"ja\"> 連絡先メールアドレスです。<br> このフィールドは、リクエストの場合は必須です。 </div> <div lang=\"en\"> Email address to send notifications.<br> This field is required in requests. </div>
     *
     * @return self
     */
    public function setNotificationEmailAddress($notification_email_address)
    {
        $this->container['notification_email_address'] = $notification_email_address;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


