<?php
/**
 * RecommendationServiceCampaignBiddingStrategyToTargetCpaCampaign
 *
 * PHP version 7.2
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Yahoo!広告 ディスプレイ広告 API リファレンス / Yahoo! JAPAN Ads Display Ads API Reference
 *
 * <div lang=\"ja\">Yahoo!広告 ディスプレイ広告 APIのWebサービスについて説明します。</div> <div lang=\"en\">Display Ads API Web Services supported in Yahoo! JAPAN Ads API.</div> <div><a target=\"_blank\" href=\"https://github.com/yahoojp-marketing/ads-display-api-documents/blob/master/design/v4/Route.yaml\">OpenAPI Specification</a></div> <div lang=\"ja\"><a target=\"_blank\" href=\"https://github.com/yahoojp-marketing/ads-display-api-documents/blob/master/bestpractice/ja\">Best Practice</a></div> <div lang=\"en\"><a target=\"_blank\" href=\"https://github.com/yahoojp-marketing/ads-display-api-documents/blob/master/bestpractice/en\">Best Practice</a></div>
 *
 * The version of the OpenAPI document: v4
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.1.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;

use \ArrayAccess;
use \OpenAPI\Client\ObjectSerializer;

/**
 * RecommendationServiceCampaignBiddingStrategyToTargetCpaCampaign Class Doc Comment
 *
 * @category Class
 * @description &lt;div lang&#x3D;\&quot;ja\&quot;&gt;RecommendationServiceCampaignBiddingStrategyToTargetCpaCampaignオブジェクトは、自動入札（コンバージョン単価の目標値）に適しているキャンペーンに関する最適化提案の詳細情報を表します。&lt;/div&gt; &lt;div lang&#x3D;\&quot;en\&quot;&gt;RecommendationServiceCampaignBiddingStrategyToTargetCpaCampaign object describes detailed information of Recommendations about the campaign that is suitable for using autobidding (target CPA).&lt;/div&gt;
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<TKey, TValue>
 * @template TKey int|null
 * @template TValue mixed|null  
 */
class RecommendationServiceCampaignBiddingStrategyToTargetCpaCampaign implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'RecommendationServiceCampaignBiddingStrategyToTargetCpaCampaign';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'recommendation_id' => 'int',
        'campaign_id' => 'int',
        'campaign_name' => 'string',
        'current_budget' => 'int',
        'current_campaign_bidding_strategy_type' => 'string',
        'current_max_cpc_bid_value' => 'int',
        'recommended_campaign_bidding_strategy_type' => 'string',
        'recommended_target_cpa_bid_value' => 'int'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'recommendation_id' => 'int64',
        'campaign_id' => 'int64',
        'campaign_name' => null,
        'current_budget' => 'int64',
        'current_campaign_bidding_strategy_type' => null,
        'current_max_cpc_bid_value' => 'int64',
        'recommended_campaign_bidding_strategy_type' => null,
        'recommended_target_cpa_bid_value' => 'int64'
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'recommendation_id' => 'recommendationId',
        'campaign_id' => 'campaignId',
        'campaign_name' => 'campaignName',
        'current_budget' => 'currentBudget',
        'current_campaign_bidding_strategy_type' => 'currentCampaignBiddingStrategyType',
        'current_max_cpc_bid_value' => 'currentMaxCpcBidValue',
        'recommended_campaign_bidding_strategy_type' => 'recommendedCampaignBiddingStrategyType',
        'recommended_target_cpa_bid_value' => 'recommendedTargetCpaBidValue'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'recommendation_id' => 'setRecommendationId',
        'campaign_id' => 'setCampaignId',
        'campaign_name' => 'setCampaignName',
        'current_budget' => 'setCurrentBudget',
        'current_campaign_bidding_strategy_type' => 'setCurrentCampaignBiddingStrategyType',
        'current_max_cpc_bid_value' => 'setCurrentMaxCpcBidValue',
        'recommended_campaign_bidding_strategy_type' => 'setRecommendedCampaignBiddingStrategyType',
        'recommended_target_cpa_bid_value' => 'setRecommendedTargetCpaBidValue'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'recommendation_id' => 'getRecommendationId',
        'campaign_id' => 'getCampaignId',
        'campaign_name' => 'getCampaignName',
        'current_budget' => 'getCurrentBudget',
        'current_campaign_bidding_strategy_type' => 'getCurrentCampaignBiddingStrategyType',
        'current_max_cpc_bid_value' => 'getCurrentMaxCpcBidValue',
        'recommended_campaign_bidding_strategy_type' => 'getRecommendedCampaignBiddingStrategyType',
        'recommended_target_cpa_bid_value' => 'getRecommendedTargetCpaBidValue'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['recommendation_id'] = $data['recommendation_id'] ?? null;
        $this->container['campaign_id'] = $data['campaign_id'] ?? null;
        $this->container['campaign_name'] = $data['campaign_name'] ?? null;
        $this->container['current_budget'] = $data['current_budget'] ?? null;
        $this->container['current_campaign_bidding_strategy_type'] = $data['current_campaign_bidding_strategy_type'] ?? null;
        $this->container['current_max_cpc_bid_value'] = $data['current_max_cpc_bid_value'] ?? null;
        $this->container['recommended_campaign_bidding_strategy_type'] = $data['recommended_campaign_bidding_strategy_type'] ?? null;
        $this->container['recommended_target_cpa_bid_value'] = $data['recommended_target_cpa_bid_value'] ?? null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets recommendation_id
     *
     * @return int|null
     */
    public function getRecommendationId()
    {
        return $this->container['recommendation_id'];
    }

    /**
     * Sets recommendation_id
     *
     * @param int|null $recommendation_id <div lang=\"ja\"> 最適化提案IDです。<br> </div> <div lang=\"en\"> Recommendation ID.<br> </div>
     *
     * @return self
     */
    public function setRecommendationId($recommendation_id)
    {
        $this->container['recommendation_id'] = $recommendation_id;

        return $this;
    }

    /**
     * Gets campaign_id
     *
     * @return int|null
     */
    public function getCampaignId()
    {
        return $this->container['campaign_id'];
    }

    /**
     * Sets campaign_id
     *
     * @param int|null $campaign_id <div lang=\"ja\"> キャンペーンIDです。<br> </div> <div lang=\"en\"> Campaign ID.<br> </div>
     *
     * @return self
     */
    public function setCampaignId($campaign_id)
    {
        $this->container['campaign_id'] = $campaign_id;

        return $this;
    }

    /**
     * Gets campaign_name
     *
     * @return string|null
     */
    public function getCampaignName()
    {
        return $this->container['campaign_name'];
    }

    /**
     * Sets campaign_name
     *
     * @param string|null $campaign_name <div lang=\"ja\"> キャンペーン名です。<br> </div> <div lang=\"en\"> Campaign Name.<br> </div>
     *
     * @return self
     */
    public function setCampaignName($campaign_name)
    {
        $this->container['campaign_name'] = $campaign_name;

        return $this;
    }

    /**
     * Gets current_budget
     *
     * @return int|null
     */
    public function getCurrentBudget()
    {
        return $this->container['current_budget'];
    }

    /**
     * Sets current_budget
     *
     * @param int|null $current_budget <div lang=\"ja\"> 現在のキャンペーン予算です。 </div> <div lang=\"en\"> Current campaign budget. </div>
     *
     * @return self
     */
    public function setCurrentBudget($current_budget)
    {
        $this->container['current_budget'] = $current_budget;

        return $this;
    }

    /**
     * Gets current_campaign_bidding_strategy_type
     *
     * @return string|null
     */
    public function getCurrentCampaignBiddingStrategyType()
    {
        return $this->container['current_campaign_bidding_strategy_type'];
    }

    /**
     * Sets current_campaign_bidding_strategy_type
     *
     * @param string|null $current_campaign_bidding_strategy_type <div lang=\"ja\"> 現在のキャンペーン入札戦略タイプです。<br> 現在は\"MAX_CPC\"のみ返却します。 </div> <div lang=\"en\"> Current campaign bidding strategy type.<br> Currently, only \"MAX_CPC\" will be returned. </div>
     *
     * @return self
     */
    public function setCurrentCampaignBiddingStrategyType($current_campaign_bidding_strategy_type)
    {
        $this->container['current_campaign_bidding_strategy_type'] = $current_campaign_bidding_strategy_type;

        return $this;
    }

    /**
     * Gets current_max_cpc_bid_value
     *
     * @return int|null
     */
    public function getCurrentMaxCpcBidValue()
    {
        return $this->container['current_max_cpc_bid_value'];
    }

    /**
     * Sets current_max_cpc_bid_value
     *
     * @param int|null $current_max_cpc_bid_value <div lang=\"ja\"> 現在のキャンペーン最大入札単価(CPC)です。 </div> <div lang=\"en\"> Current max bid of campaign (CPC). </div>
     *
     * @return self
     */
    public function setCurrentMaxCpcBidValue($current_max_cpc_bid_value)
    {
        $this->container['current_max_cpc_bid_value'] = $current_max_cpc_bid_value;

        return $this;
    }

    /**
     * Gets recommended_campaign_bidding_strategy_type
     *
     * @return string|null
     */
    public function getRecommendedCampaignBiddingStrategyType()
    {
        return $this->container['recommended_campaign_bidding_strategy_type'];
    }

    /**
     * Sets recommended_campaign_bidding_strategy_type
     *
     * @param string|null $recommended_campaign_bidding_strategy_type <div lang=\"ja\"> 推奨するキャンペーン入札戦略タイプです。<br> 現在は\"AUTO\"のみ返却します。 </div> <div lang=\"en\"> Recommended campaign bidding strategy type.<br> Currently, only \"AUTO\" will be returned. </div>
     *
     * @return self
     */
    public function setRecommendedCampaignBiddingStrategyType($recommended_campaign_bidding_strategy_type)
    {
        $this->container['recommended_campaign_bidding_strategy_type'] = $recommended_campaign_bidding_strategy_type;

        return $this;
    }

    /**
     * Gets recommended_target_cpa_bid_value
     *
     * @return int|null
     */
    public function getRecommendedTargetCpaBidValue()
    {
        return $this->container['recommended_target_cpa_bid_value'];
    }

    /**
     * Sets recommended_target_cpa_bid_value
     *
     * @param int|null $recommended_target_cpa_bid_value <div lang=\"ja\"> 推奨するキャンペーン目標単価(tCPA)です。 </div> <div lang=\"en\"> Recommended target bid of campaign (tCPA). </div>
     *
     * @return self
     */
    public function setRecommendedTargetCpaBidValue($recommended_target_cpa_bid_value)
    {
        $this->container['recommended_target_cpa_bid_value'] = $recommended_target_cpa_bid_value;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


