<?php
/**
 * RetargetingListServiceTargetList
 *
 * PHP version 7.2
 *
 * @category Class
 * @package  YahooAdsDisplayApi\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Yahoo!広告 ディスプレイ広告 API リファレンス / Yahoo! JAPAN Ads Display Ads API Reference
 *
 * <div lang=\"ja\">Yahoo!広告 ディスプレイ広告 APIのWebサービスについて説明します。</div> <div lang=\"en\">Display Ads API Web Services supported in Yahoo! JAPAN Ads API.</div> <div><a target=\"_blank\" href=\"https://github.com/yahoojp-marketing/ads-display-api-documents/blob/master/design/v4/Route.yaml\">OpenAPI Specification</a></div> <div lang=\"ja\"><a target=\"_blank\" href=\"https://github.com/yahoojp-marketing/ads-display-api-documents/blob/master/bestpractice/ja\">Best Practice</a></div> <div lang=\"en\"><a target=\"_blank\" href=\"https://github.com/yahoojp-marketing/ads-display-api-documents/blob/master/bestpractice/en\">Best Practice</a></div>
 *
 * The version of the OpenAPI document: v4
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.1.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace YahooAdsDisplayApi\Client\Model;

use \ArrayAccess;
use \YahooAdsDisplayApi\Client\ObjectSerializer;

/**
 * RetargetingListServiceTargetList Class Doc Comment
 *
 * @category Class
 * @description &lt;div lang&#x3D;\&quot;ja\&quot;&gt; RetargetingListServiceTargetListオブジェクトは、リターゲティングのターゲット種類とターゲットリストの情報を表します。&lt;br&gt; このフィールドは、ADDおよびSET時に必須となり、REMOVE時に無視されます。 &lt;/div&gt; &lt;div lang&#x3D;\&quot;en\&quot;&gt; RetargetingListServiceTargetList object displays the types of target and target list for site retargeting. &lt;br&gt; This field is required in ADD and SET operation, and will be ignored in REMOVE operation. &lt;/div&gt;
 * @package  YahooAdsDisplayApi\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<TKey, TValue>
 * @template TKey int|null
 * @template TValue mixed|null  
 */
class RetargetingListServiceTargetList implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'RetargetingListServiceTargetList';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'combination_target_list' => '\YahooAdsDisplayApi\Client\Model\RetargetingListServiceCombinationTargetList',
        'custom_audience_target_list' => '\YahooAdsDisplayApi\Client\Model\RetargetingListServiceCustomAudienceTargetList',
        'rule_target_list' => '\YahooAdsDisplayApi\Client\Model\RetargetingListServiceRuleTargetList',
        'similarity_target_list' => '\YahooAdsDisplayApi\Client\Model\RetargetingListServiceSimilarityTargetList',
        'target_list_type' => '\YahooAdsDisplayApi\Client\Model\RetargetingListServiceTargetListType'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'combination_target_list' => null,
        'custom_audience_target_list' => null,
        'rule_target_list' => null,
        'similarity_target_list' => null,
        'target_list_type' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'combination_target_list' => 'combinationTargetList',
        'custom_audience_target_list' => 'customAudienceTargetList',
        'rule_target_list' => 'ruleTargetList',
        'similarity_target_list' => 'similarityTargetList',
        'target_list_type' => 'targetListType'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'combination_target_list' => 'setCombinationTargetList',
        'custom_audience_target_list' => 'setCustomAudienceTargetList',
        'rule_target_list' => 'setRuleTargetList',
        'similarity_target_list' => 'setSimilarityTargetList',
        'target_list_type' => 'setTargetListType'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'combination_target_list' => 'getCombinationTargetList',
        'custom_audience_target_list' => 'getCustomAudienceTargetList',
        'rule_target_list' => 'getRuleTargetList',
        'similarity_target_list' => 'getSimilarityTargetList',
        'target_list_type' => 'getTargetListType'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['combination_target_list'] = $data['combination_target_list'] ?? null;
        $this->container['custom_audience_target_list'] = $data['custom_audience_target_list'] ?? null;
        $this->container['rule_target_list'] = $data['rule_target_list'] ?? null;
        $this->container['similarity_target_list'] = $data['similarity_target_list'] ?? null;
        $this->container['target_list_type'] = $data['target_list_type'] ?? null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['target_list_type'] === null) {
            $invalidProperties[] = "'target_list_type' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets combination_target_list
     *
     * @return \YahooAdsDisplayApi\Client\Model\RetargetingListServiceCombinationTargetList|null
     */
    public function getCombinationTargetList()
    {
        return $this->container['combination_target_list'];
    }

    /**
     * Sets combination_target_list
     *
     * @param \YahooAdsDisplayApi\Client\Model\RetargetingListServiceCombinationTargetList|null $combination_target_list combination_target_list
     *
     * @return self
     */
    public function setCombinationTargetList($combination_target_list)
    {
        $this->container['combination_target_list'] = $combination_target_list;

        return $this;
    }

    /**
     * Gets custom_audience_target_list
     *
     * @return \YahooAdsDisplayApi\Client\Model\RetargetingListServiceCustomAudienceTargetList|null
     */
    public function getCustomAudienceTargetList()
    {
        return $this->container['custom_audience_target_list'];
    }

    /**
     * Sets custom_audience_target_list
     *
     * @param \YahooAdsDisplayApi\Client\Model\RetargetingListServiceCustomAudienceTargetList|null $custom_audience_target_list custom_audience_target_list
     *
     * @return self
     */
    public function setCustomAudienceTargetList($custom_audience_target_list)
    {
        $this->container['custom_audience_target_list'] = $custom_audience_target_list;

        return $this;
    }

    /**
     * Gets rule_target_list
     *
     * @return \YahooAdsDisplayApi\Client\Model\RetargetingListServiceRuleTargetList|null
     */
    public function getRuleTargetList()
    {
        return $this->container['rule_target_list'];
    }

    /**
     * Sets rule_target_list
     *
     * @param \YahooAdsDisplayApi\Client\Model\RetargetingListServiceRuleTargetList|null $rule_target_list rule_target_list
     *
     * @return self
     */
    public function setRuleTargetList($rule_target_list)
    {
        $this->container['rule_target_list'] = $rule_target_list;

        return $this;
    }

    /**
     * Gets similarity_target_list
     *
     * @return \YahooAdsDisplayApi\Client\Model\RetargetingListServiceSimilarityTargetList|null
     */
    public function getSimilarityTargetList()
    {
        return $this->container['similarity_target_list'];
    }

    /**
     * Sets similarity_target_list
     *
     * @param \YahooAdsDisplayApi\Client\Model\RetargetingListServiceSimilarityTargetList|null $similarity_target_list similarity_target_list
     *
     * @return self
     */
    public function setSimilarityTargetList($similarity_target_list)
    {
        $this->container['similarity_target_list'] = $similarity_target_list;

        return $this;
    }

    /**
     * Gets target_list_type
     *
     * @return \YahooAdsDisplayApi\Client\Model\RetargetingListServiceTargetListType
     */
    public function getTargetListType()
    {
        return $this->container['target_list_type'];
    }

    /**
     * Sets target_list_type
     *
     * @param \YahooAdsDisplayApi\Client\Model\RetargetingListServiceTargetListType $target_list_type target_list_type
     *
     * @return self
     */
    public function setTargetListType($target_list_type)
    {
        $this->container['target_list_type'] = $target_list_type;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


