<?php
/**
 * SearchKeywordIdeaServiceSelector
 *
 * PHP version 7.2
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Yahoo!広告 ディスプレイ広告 API リファレンス / Yahoo! JAPAN Ads Display Ads API Reference
 *
 * <div lang=\"ja\">Yahoo!広告 ディスプレイ広告 APIのWebサービスについて説明します。</div> <div lang=\"en\">Display Ads API Web Services supported in Yahoo! JAPAN Ads API.</div> <div><a target=\"_blank\" href=\"https://github.com/yahoojp-marketing/ads-display-api-documents/blob/master/design/v4/Route.yaml\">OpenAPI Specification</a></div> <div lang=\"ja\"><a target=\"_blank\" href=\"https://github.com/yahoojp-marketing/ads-display-api-documents/blob/master/bestpractice/ja\">Best Practice</a></div> <div lang=\"en\"><a target=\"_blank\" href=\"https://github.com/yahoojp-marketing/ads-display-api-documents/blob/master/bestpractice/en\">Best Practice</a></div>
 *
 * The version of the OpenAPI document: v4
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.1.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;

use \ArrayAccess;
use \OpenAPI\Client\ObjectSerializer;

/**
 * SearchKeywordIdeaServiceSelector Class Doc Comment
 *
 * @category Class
 * @description &lt;div lang&#x3D;\&quot;ja\&quot;&gt;SearchKeywordIdeaServiceSelectorオブジェクトは、サーチターゲティング対象キーワードのリストを表します。&lt;/div&gt; &lt;div lang&#x3D;\&quot;en\&quot;&gt;SearchKeywordIdeaServiceSelector object displays the list of keyword for search targeting.&lt;/div&gt;
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<TKey, TValue>
 * @template TKey int|null
 * @template TValue mixed|null  
 */
class SearchKeywordIdeaServiceSelector implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'SearchKeywordIdeaServiceSelector';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'keyword_frequency' => '\OpenAPI\Client\Model\SearchKeywordIdeaServiceKeywordFrequency',
        'keyword_ids' => 'int[]',
        'keyword_recency' => '\OpenAPI\Client\Model\SearchKeywordIdeaServiceKeywordRecency',
        'keywords' => 'string[]',
        'match_type' => '\OpenAPI\Client\Model\SearchKeywordIdeaServiceMatchType',
        'number_results' => 'int',
        'sort_field' => '\OpenAPI\Client\Model\SearchKeywordIdeaServiceSortField',
        'sort_type' => '\OpenAPI\Client\Model\SearchKeywordIdeaServiceSortType',
        'start_index' => 'int',
        'availability_status' => '\OpenAPI\Client\Model\SearchKeywordIdeaServiceAvailabilityStatus'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'keyword_frequency' => null,
        'keyword_ids' => 'int64',
        'keyword_recency' => null,
        'keywords' => null,
        'match_type' => null,
        'number_results' => 'int32',
        'sort_field' => null,
        'sort_type' => null,
        'start_index' => 'int32',
        'availability_status' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'keyword_frequency' => 'keywordFrequency',
        'keyword_ids' => 'keywordIds',
        'keyword_recency' => 'keywordRecency',
        'keywords' => 'keywords',
        'match_type' => 'matchType',
        'number_results' => 'numberResults',
        'sort_field' => 'sortField',
        'sort_type' => 'sortType',
        'start_index' => 'startIndex',
        'availability_status' => 'availabilityStatus'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'keyword_frequency' => 'setKeywordFrequency',
        'keyword_ids' => 'setKeywordIds',
        'keyword_recency' => 'setKeywordRecency',
        'keywords' => 'setKeywords',
        'match_type' => 'setMatchType',
        'number_results' => 'setNumberResults',
        'sort_field' => 'setSortField',
        'sort_type' => 'setSortType',
        'start_index' => 'setStartIndex',
        'availability_status' => 'setAvailabilityStatus'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'keyword_frequency' => 'getKeywordFrequency',
        'keyword_ids' => 'getKeywordIds',
        'keyword_recency' => 'getKeywordRecency',
        'keywords' => 'getKeywords',
        'match_type' => 'getMatchType',
        'number_results' => 'getNumberResults',
        'sort_field' => 'getSortField',
        'sort_type' => 'getSortType',
        'start_index' => 'getStartIndex',
        'availability_status' => 'getAvailabilityStatus'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['keyword_frequency'] = $data['keyword_frequency'] ?? null;
        $this->container['keyword_ids'] = $data['keyword_ids'] ?? null;
        $this->container['keyword_recency'] = $data['keyword_recency'] ?? null;
        $this->container['keywords'] = $data['keywords'] ?? null;
        $this->container['match_type'] = $data['match_type'] ?? null;
        $this->container['number_results'] = $data['number_results'] ?? 1000;
        $this->container['sort_field'] = $data['sort_field'] ?? null;
        $this->container['sort_type'] = $data['sort_type'] ?? null;
        $this->container['start_index'] = $data['start_index'] ?? 1;
        $this->container['availability_status'] = $data['availability_status'] ?? null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if (!is_null($this->container['keyword_ids']) && (count($this->container['keyword_ids']) > 500)) {
            $invalidProperties[] = "invalid value for 'keyword_ids', number of items must be less than or equal to 500.";
        }

        if (!is_null($this->container['keywords']) && (count($this->container['keywords']) > 200)) {
            $invalidProperties[] = "invalid value for 'keywords', number of items must be less than or equal to 200.";
        }

        if (!is_null($this->container['number_results']) && ($this->container['number_results'] > 1000)) {
            $invalidProperties[] = "invalid value for 'number_results', must be smaller than or equal to 1000.";
        }

        if (!is_null($this->container['number_results']) && ($this->container['number_results'] < 1)) {
            $invalidProperties[] = "invalid value for 'number_results', must be bigger than or equal to 1.";
        }

        if (!is_null($this->container['start_index']) && ($this->container['start_index'] < 1)) {
            $invalidProperties[] = "invalid value for 'start_index', must be bigger than or equal to 1.";
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets keyword_frequency
     *
     * @return \OpenAPI\Client\Model\SearchKeywordIdeaServiceKeywordFrequency|null
     */
    public function getKeywordFrequency()
    {
        return $this->container['keyword_frequency'];
    }

    /**
     * Sets keyword_frequency
     *
     * @param \OpenAPI\Client\Model\SearchKeywordIdeaServiceKeywordFrequency|null $keyword_frequency keyword_frequency
     *
     * @return self
     */
    public function setKeywordFrequency($keyword_frequency)
    {
        $this->container['keyword_frequency'] = $keyword_frequency;

        return $this;
    }

    /**
     * Gets keyword_ids
     *
     * @return int[]|null
     */
    public function getKeywordIds()
    {
        return $this->container['keyword_ids'];
    }

    /**
     * Sets keyword_ids
     *
     * @param int[]|null $keyword_ids <div lang=\"ja\"> 検索条件：キーワードID<br> ※キーワード検索用<br> ※キーワード、キーワードIDの同時指定はできません。 </div> <div lang=\"en\">Search condition : Keyword ID.<br> *Keyword for searching.<br> *Can not specify Keyword and Keyword ID at the same time. </div>
     *
     * @return self
     */
    public function setKeywordIds($keyword_ids)
    {

        if (!is_null($keyword_ids) && (count($keyword_ids) > 500)) {
            throw new \InvalidArgumentException('invalid value for $keyword_ids when calling SearchKeywordIdeaServiceSelector., number of items must be less than or equal to 500.');
        }
        $this->container['keyword_ids'] = $keyword_ids;

        return $this;
    }

    /**
     * Gets keyword_recency
     *
     * @return \OpenAPI\Client\Model\SearchKeywordIdeaServiceKeywordRecency|null
     */
    public function getKeywordRecency()
    {
        return $this->container['keyword_recency'];
    }

    /**
     * Sets keyword_recency
     *
     * @param \OpenAPI\Client\Model\SearchKeywordIdeaServiceKeywordRecency|null $keyword_recency keyword_recency
     *
     * @return self
     */
    public function setKeywordRecency($keyword_recency)
    {
        $this->container['keyword_recency'] = $keyword_recency;

        return $this;
    }

    /**
     * Gets keywords
     *
     * @return string[]|null
     */
    public function getKeywords()
    {
        return $this->container['keywords'];
    }

    /**
     * Sets keywords
     *
     * @param string[]|null $keywords <div lang=\"ja\"> 検索条件：キーワード<br> ※キーワード提案用<br> ※キーワード、キーワードIDの同時指定はできません。 </div> <div lang=\"en\"> Search condition : Keyword.<br> *Keyword for suggesting.<br> *Can not specify Keyword and Keyword ID at the same time. </div>
     *
     * @return self
     */
    public function setKeywords($keywords)
    {

        if (!is_null($keywords) && (count($keywords) > 200)) {
            throw new \InvalidArgumentException('invalid value for $keywords when calling SearchKeywordIdeaServiceSelector., number of items must be less than or equal to 200.');
        }
        $this->container['keywords'] = $keywords;

        return $this;
    }

    /**
     * Gets match_type
     *
     * @return \OpenAPI\Client\Model\SearchKeywordIdeaServiceMatchType|null
     */
    public function getMatchType()
    {
        return $this->container['match_type'];
    }

    /**
     * Sets match_type
     *
     * @param \OpenAPI\Client\Model\SearchKeywordIdeaServiceMatchType|null $match_type match_type
     *
     * @return self
     */
    public function setMatchType($match_type)
    {
        $this->container['match_type'] = $match_type;

        return $this;
    }

    /**
     * Gets number_results
     *
     * @return int|null
     */
    public function getNumberResults()
    {
        return $this->container['number_results'];
    }

    /**
     * Sets number_results
     *
     * @param int|null $number_results <div lang=\"ja\">ページの最大件数です。このフィールドは、1以上を指定する必要があります。</div> <div lang=\"en\">Maximum number of results to return in this page. This field must be greater than or equal to 1. Also see Entity Limits per operation.</div>
     *
     * @return self
     */
    public function setNumberResults($number_results)
    {

        if (!is_null($number_results) && ($number_results > 1000)) {
            throw new \InvalidArgumentException('invalid value for $number_results when calling SearchKeywordIdeaServiceSelector., must be smaller than or equal to 1000.');
        }
        if (!is_null($number_results) && ($number_results < 1)) {
            throw new \InvalidArgumentException('invalid value for $number_results when calling SearchKeywordIdeaServiceSelector., must be bigger than or equal to 1.');
        }

        $this->container['number_results'] = $number_results;

        return $this;
    }

    /**
     * Gets sort_field
     *
     * @return \OpenAPI\Client\Model\SearchKeywordIdeaServiceSortField|null
     */
    public function getSortField()
    {
        return $this->container['sort_field'];
    }

    /**
     * Sets sort_field
     *
     * @param \OpenAPI\Client\Model\SearchKeywordIdeaServiceSortField|null $sort_field sort_field
     *
     * @return self
     */
    public function setSortField($sort_field)
    {
        $this->container['sort_field'] = $sort_field;

        return $this;
    }

    /**
     * Gets sort_type
     *
     * @return \OpenAPI\Client\Model\SearchKeywordIdeaServiceSortType|null
     */
    public function getSortType()
    {
        return $this->container['sort_type'];
    }

    /**
     * Sets sort_type
     *
     * @param \OpenAPI\Client\Model\SearchKeywordIdeaServiceSortType|null $sort_type sort_type
     *
     * @return self
     */
    public function setSortType($sort_type)
    {
        $this->container['sort_type'] = $sort_type;

        return $this;
    }

    /**
     * Gets start_index
     *
     * @return int|null
     */
    public function getStartIndex()
    {
        return $this->container['start_index'];
    }

    /**
     * Sets start_index
     *
     * @param int|null $start_index <div lang=\"ja\">ページの先頭のインデックスです。このフィールドは、1以上を指定する必要があります。</div> <div lang=\"en\">Index of the first result to return in this page. This field must be greater than or equal to 1.</div>
     *
     * @return self
     */
    public function setStartIndex($start_index)
    {

        if (!is_null($start_index) && ($start_index < 1)) {
            throw new \InvalidArgumentException('invalid value for $start_index when calling SearchKeywordIdeaServiceSelector., must be bigger than or equal to 1.');
        }

        $this->container['start_index'] = $start_index;

        return $this;
    }

    /**
     * Gets availability_status
     *
     * @return \OpenAPI\Client\Model\SearchKeywordIdeaServiceAvailabilityStatus|null
     */
    public function getAvailabilityStatus()
    {
        return $this->container['availability_status'];
    }

    /**
     * Sets availability_status
     *
     * @param \OpenAPI\Client\Model\SearchKeywordIdeaServiceAvailabilityStatus|null $availability_status availability_status
     *
     * @return self
     */
    public function setAvailabilityStatus($availability_status)
    {
        $this->container['availability_status'] = $availability_status;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


