<?php
/**
 * StatsServiceTarget
 *
 * PHP version 7.2
 *
 * @category Class
 * @package  YahooAdsDisplayApi\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Yahoo!広告 ディスプレイ広告 API リファレンス / Yahoo! JAPAN Ads Display Ads API Reference
 *
 * <div lang=\"ja\">Yahoo!広告 ディスプレイ広告 APIのWebサービスについて説明します。</div> <div lang=\"en\">Display Ads API Web Services supported in Yahoo! JAPAN Ads API.</div> <div><a target=\"_blank\" href=\"https://github.com/yahoojp-marketing/ads-display-api-documents/blob/master/design/v4/Route.yaml\">OpenAPI Specification</a></div> <div lang=\"ja\"><a target=\"_blank\" href=\"https://github.com/yahoojp-marketing/ads-display-api-documents/blob/master/bestpractice/ja\">Best Practice</a></div> <div lang=\"en\"><a target=\"_blank\" href=\"https://github.com/yahoojp-marketing/ads-display-api-documents/blob/master/bestpractice/en\">Best Practice</a></div>
 *
 * The version of the OpenAPI document: v4
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.1.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace YahooAdsDisplayApi\Client\Model;

use \ArrayAccess;
use \YahooAdsDisplayApi\Client\ObjectSerializer;

/**
 * StatsServiceTarget Class Doc Comment
 *
 * @category Class
 * @description &lt;div lang&#x3D;\&quot;ja\&quot;&gt;StatsServiceTargetオブジェクトは、ターゲット設定情報を保持します。&lt;/div&gt; &lt;div lang&#x3D;\&quot;en\&quot;&gt;StatsServiceTarget object holds configuration information of StatsServiceTargeting.&lt;/div&gt;
 * @package  YahooAdsDisplayApi\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<TKey, TValue>
 * @template TKey int|null
 * @template TValue mixed|null  
 */
class StatsServiceTarget implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'StatsServiceTarget';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'ad_schedule_target' => '\YahooAdsDisplayApi\Client\Model\StatsServiceAdScheduleTarget',
        'age_target' => '\YahooAdsDisplayApi\Client\Model\StatsServiceAgeTarget',
        'app_target' => '\YahooAdsDisplayApi\Client\Model\StatsServiceAppTarget',
        'audience_category_target' => '\YahooAdsDisplayApi\Client\Model\StatsServiceAudienceCategoryTarget',
        'carrier_target' => '\YahooAdsDisplayApi\Client\Model\StatsServiceCarrierTarget',
        'device_target' => '\YahooAdsDisplayApi\Client\Model\StatsServiceDeviceTarget',
        'gender_target' => '\YahooAdsDisplayApi\Client\Model\StatsServiceGenderTarget',
        'geo_target' => '\YahooAdsDisplayApi\Client\Model\StatsServiceGeoTarget',
        'interest_category_target' => '\YahooAdsDisplayApi\Client\Model\StatsServiceInterestCategoryTarget',
        'os_target' => '\YahooAdsDisplayApi\Client\Model\StatsServiceOsTarget',
        'os_version_target' => '\YahooAdsDisplayApi\Client\Model\StatsServiceOsVersionTarget',
        'placement_target' => '\YahooAdsDisplayApi\Client\Model\StatsServicePlacementTarget',
        'search_target' => '\YahooAdsDisplayApi\Client\Model\StatsServiceSearchTarget',
        'site_category_target' => '\YahooAdsDisplayApi\Client\Model\StatsServiceSiteCategoryTarget',
        'site_retargeting_target' => '\YahooAdsDisplayApi\Client\Model\StatsServiceSiteRetargetingTarget',
        'target_id' => 'string',
        'target_setting' => '\YahooAdsDisplayApi\Client\Model\StatsServiceTargetSetting',
        'target_type' => '\YahooAdsDisplayApi\Client\Model\StatsServiceTargetType'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'ad_schedule_target' => null,
        'age_target' => null,
        'app_target' => null,
        'audience_category_target' => null,
        'carrier_target' => null,
        'device_target' => null,
        'gender_target' => null,
        'geo_target' => null,
        'interest_category_target' => null,
        'os_target' => null,
        'os_version_target' => null,
        'placement_target' => null,
        'search_target' => null,
        'site_category_target' => null,
        'site_retargeting_target' => null,
        'target_id' => null,
        'target_setting' => null,
        'target_type' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'ad_schedule_target' => 'adScheduleTarget',
        'age_target' => 'ageTarget',
        'app_target' => 'appTarget',
        'audience_category_target' => 'audienceCategoryTarget',
        'carrier_target' => 'carrierTarget',
        'device_target' => 'deviceTarget',
        'gender_target' => 'genderTarget',
        'geo_target' => 'geoTarget',
        'interest_category_target' => 'interestCategoryTarget',
        'os_target' => 'osTarget',
        'os_version_target' => 'osVersionTarget',
        'placement_target' => 'placementTarget',
        'search_target' => 'searchTarget',
        'site_category_target' => 'siteCategoryTarget',
        'site_retargeting_target' => 'siteRetargetingTarget',
        'target_id' => 'targetId',
        'target_setting' => 'targetSetting',
        'target_type' => 'targetType'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'ad_schedule_target' => 'setAdScheduleTarget',
        'age_target' => 'setAgeTarget',
        'app_target' => 'setAppTarget',
        'audience_category_target' => 'setAudienceCategoryTarget',
        'carrier_target' => 'setCarrierTarget',
        'device_target' => 'setDeviceTarget',
        'gender_target' => 'setGenderTarget',
        'geo_target' => 'setGeoTarget',
        'interest_category_target' => 'setInterestCategoryTarget',
        'os_target' => 'setOsTarget',
        'os_version_target' => 'setOsVersionTarget',
        'placement_target' => 'setPlacementTarget',
        'search_target' => 'setSearchTarget',
        'site_category_target' => 'setSiteCategoryTarget',
        'site_retargeting_target' => 'setSiteRetargetingTarget',
        'target_id' => 'setTargetId',
        'target_setting' => 'setTargetSetting',
        'target_type' => 'setTargetType'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'ad_schedule_target' => 'getAdScheduleTarget',
        'age_target' => 'getAgeTarget',
        'app_target' => 'getAppTarget',
        'audience_category_target' => 'getAudienceCategoryTarget',
        'carrier_target' => 'getCarrierTarget',
        'device_target' => 'getDeviceTarget',
        'gender_target' => 'getGenderTarget',
        'geo_target' => 'getGeoTarget',
        'interest_category_target' => 'getInterestCategoryTarget',
        'os_target' => 'getOsTarget',
        'os_version_target' => 'getOsVersionTarget',
        'placement_target' => 'getPlacementTarget',
        'search_target' => 'getSearchTarget',
        'site_category_target' => 'getSiteCategoryTarget',
        'site_retargeting_target' => 'getSiteRetargetingTarget',
        'target_id' => 'getTargetId',
        'target_setting' => 'getTargetSetting',
        'target_type' => 'getTargetType'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['ad_schedule_target'] = $data['ad_schedule_target'] ?? null;
        $this->container['age_target'] = $data['age_target'] ?? null;
        $this->container['app_target'] = $data['app_target'] ?? null;
        $this->container['audience_category_target'] = $data['audience_category_target'] ?? null;
        $this->container['carrier_target'] = $data['carrier_target'] ?? null;
        $this->container['device_target'] = $data['device_target'] ?? null;
        $this->container['gender_target'] = $data['gender_target'] ?? null;
        $this->container['geo_target'] = $data['geo_target'] ?? null;
        $this->container['interest_category_target'] = $data['interest_category_target'] ?? null;
        $this->container['os_target'] = $data['os_target'] ?? null;
        $this->container['os_version_target'] = $data['os_version_target'] ?? null;
        $this->container['placement_target'] = $data['placement_target'] ?? null;
        $this->container['search_target'] = $data['search_target'] ?? null;
        $this->container['site_category_target'] = $data['site_category_target'] ?? null;
        $this->container['site_retargeting_target'] = $data['site_retargeting_target'] ?? null;
        $this->container['target_id'] = $data['target_id'] ?? null;
        $this->container['target_setting'] = $data['target_setting'] ?? null;
        $this->container['target_type'] = $data['target_type'] ?? null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets ad_schedule_target
     *
     * @return \YahooAdsDisplayApi\Client\Model\StatsServiceAdScheduleTarget|null
     */
    public function getAdScheduleTarget()
    {
        return $this->container['ad_schedule_target'];
    }

    /**
     * Sets ad_schedule_target
     *
     * @param \YahooAdsDisplayApi\Client\Model\StatsServiceAdScheduleTarget|null $ad_schedule_target ad_schedule_target
     *
     * @return self
     */
    public function setAdScheduleTarget($ad_schedule_target)
    {
        $this->container['ad_schedule_target'] = $ad_schedule_target;

        return $this;
    }

    /**
     * Gets age_target
     *
     * @return \YahooAdsDisplayApi\Client\Model\StatsServiceAgeTarget|null
     */
    public function getAgeTarget()
    {
        return $this->container['age_target'];
    }

    /**
     * Sets age_target
     *
     * @param \YahooAdsDisplayApi\Client\Model\StatsServiceAgeTarget|null $age_target age_target
     *
     * @return self
     */
    public function setAgeTarget($age_target)
    {
        $this->container['age_target'] = $age_target;

        return $this;
    }

    /**
     * Gets app_target
     *
     * @return \YahooAdsDisplayApi\Client\Model\StatsServiceAppTarget|null
     */
    public function getAppTarget()
    {
        return $this->container['app_target'];
    }

    /**
     * Sets app_target
     *
     * @param \YahooAdsDisplayApi\Client\Model\StatsServiceAppTarget|null $app_target app_target
     *
     * @return self
     */
    public function setAppTarget($app_target)
    {
        $this->container['app_target'] = $app_target;

        return $this;
    }

    /**
     * Gets audience_category_target
     *
     * @return \YahooAdsDisplayApi\Client\Model\StatsServiceAudienceCategoryTarget|null
     */
    public function getAudienceCategoryTarget()
    {
        return $this->container['audience_category_target'];
    }

    /**
     * Sets audience_category_target
     *
     * @param \YahooAdsDisplayApi\Client\Model\StatsServiceAudienceCategoryTarget|null $audience_category_target audience_category_target
     *
     * @return self
     */
    public function setAudienceCategoryTarget($audience_category_target)
    {
        $this->container['audience_category_target'] = $audience_category_target;

        return $this;
    }

    /**
     * Gets carrier_target
     *
     * @return \YahooAdsDisplayApi\Client\Model\StatsServiceCarrierTarget|null
     */
    public function getCarrierTarget()
    {
        return $this->container['carrier_target'];
    }

    /**
     * Sets carrier_target
     *
     * @param \YahooAdsDisplayApi\Client\Model\StatsServiceCarrierTarget|null $carrier_target carrier_target
     *
     * @return self
     */
    public function setCarrierTarget($carrier_target)
    {
        $this->container['carrier_target'] = $carrier_target;

        return $this;
    }

    /**
     * Gets device_target
     *
     * @return \YahooAdsDisplayApi\Client\Model\StatsServiceDeviceTarget|null
     */
    public function getDeviceTarget()
    {
        return $this->container['device_target'];
    }

    /**
     * Sets device_target
     *
     * @param \YahooAdsDisplayApi\Client\Model\StatsServiceDeviceTarget|null $device_target device_target
     *
     * @return self
     */
    public function setDeviceTarget($device_target)
    {
        $this->container['device_target'] = $device_target;

        return $this;
    }

    /**
     * Gets gender_target
     *
     * @return \YahooAdsDisplayApi\Client\Model\StatsServiceGenderTarget|null
     */
    public function getGenderTarget()
    {
        return $this->container['gender_target'];
    }

    /**
     * Sets gender_target
     *
     * @param \YahooAdsDisplayApi\Client\Model\StatsServiceGenderTarget|null $gender_target gender_target
     *
     * @return self
     */
    public function setGenderTarget($gender_target)
    {
        $this->container['gender_target'] = $gender_target;

        return $this;
    }

    /**
     * Gets geo_target
     *
     * @return \YahooAdsDisplayApi\Client\Model\StatsServiceGeoTarget|null
     */
    public function getGeoTarget()
    {
        return $this->container['geo_target'];
    }

    /**
     * Sets geo_target
     *
     * @param \YahooAdsDisplayApi\Client\Model\StatsServiceGeoTarget|null $geo_target geo_target
     *
     * @return self
     */
    public function setGeoTarget($geo_target)
    {
        $this->container['geo_target'] = $geo_target;

        return $this;
    }

    /**
     * Gets interest_category_target
     *
     * @return \YahooAdsDisplayApi\Client\Model\StatsServiceInterestCategoryTarget|null
     */
    public function getInterestCategoryTarget()
    {
        return $this->container['interest_category_target'];
    }

    /**
     * Sets interest_category_target
     *
     * @param \YahooAdsDisplayApi\Client\Model\StatsServiceInterestCategoryTarget|null $interest_category_target interest_category_target
     *
     * @return self
     */
    public function setInterestCategoryTarget($interest_category_target)
    {
        $this->container['interest_category_target'] = $interest_category_target;

        return $this;
    }

    /**
     * Gets os_target
     *
     * @return \YahooAdsDisplayApi\Client\Model\StatsServiceOsTarget|null
     */
    public function getOsTarget()
    {
        return $this->container['os_target'];
    }

    /**
     * Sets os_target
     *
     * @param \YahooAdsDisplayApi\Client\Model\StatsServiceOsTarget|null $os_target os_target
     *
     * @return self
     */
    public function setOsTarget($os_target)
    {
        $this->container['os_target'] = $os_target;

        return $this;
    }

    /**
     * Gets os_version_target
     *
     * @return \YahooAdsDisplayApi\Client\Model\StatsServiceOsVersionTarget|null
     */
    public function getOsVersionTarget()
    {
        return $this->container['os_version_target'];
    }

    /**
     * Sets os_version_target
     *
     * @param \YahooAdsDisplayApi\Client\Model\StatsServiceOsVersionTarget|null $os_version_target os_version_target
     *
     * @return self
     */
    public function setOsVersionTarget($os_version_target)
    {
        $this->container['os_version_target'] = $os_version_target;

        return $this;
    }

    /**
     * Gets placement_target
     *
     * @return \YahooAdsDisplayApi\Client\Model\StatsServicePlacementTarget|null
     */
    public function getPlacementTarget()
    {
        return $this->container['placement_target'];
    }

    /**
     * Sets placement_target
     *
     * @param \YahooAdsDisplayApi\Client\Model\StatsServicePlacementTarget|null $placement_target placement_target
     *
     * @return self
     */
    public function setPlacementTarget($placement_target)
    {
        $this->container['placement_target'] = $placement_target;

        return $this;
    }

    /**
     * Gets search_target
     *
     * @return \YahooAdsDisplayApi\Client\Model\StatsServiceSearchTarget|null
     */
    public function getSearchTarget()
    {
        return $this->container['search_target'];
    }

    /**
     * Sets search_target
     *
     * @param \YahooAdsDisplayApi\Client\Model\StatsServiceSearchTarget|null $search_target search_target
     *
     * @return self
     */
    public function setSearchTarget($search_target)
    {
        $this->container['search_target'] = $search_target;

        return $this;
    }

    /**
     * Gets site_category_target
     *
     * @return \YahooAdsDisplayApi\Client\Model\StatsServiceSiteCategoryTarget|null
     */
    public function getSiteCategoryTarget()
    {
        return $this->container['site_category_target'];
    }

    /**
     * Sets site_category_target
     *
     * @param \YahooAdsDisplayApi\Client\Model\StatsServiceSiteCategoryTarget|null $site_category_target site_category_target
     *
     * @return self
     */
    public function setSiteCategoryTarget($site_category_target)
    {
        $this->container['site_category_target'] = $site_category_target;

        return $this;
    }

    /**
     * Gets site_retargeting_target
     *
     * @return \YahooAdsDisplayApi\Client\Model\StatsServiceSiteRetargetingTarget|null
     */
    public function getSiteRetargetingTarget()
    {
        return $this->container['site_retargeting_target'];
    }

    /**
     * Sets site_retargeting_target
     *
     * @param \YahooAdsDisplayApi\Client\Model\StatsServiceSiteRetargetingTarget|null $site_retargeting_target site_retargeting_target
     *
     * @return self
     */
    public function setSiteRetargetingTarget($site_retargeting_target)
    {
        $this->container['site_retargeting_target'] = $site_retargeting_target;

        return $this;
    }

    /**
     * Gets target_id
     *
     * @return string|null
     */
    public function getTargetId()
    {
        return $this->container['target_id'];
    }

    /**
     * Sets target_id
     *
     * @param string|null $target_id <div lang=\"ja\">ターゲットID</div> <div lang=\"en\">StatsServiceTarget ID</div>
     *
     * @return self
     */
    public function setTargetId($target_id)
    {
        $this->container['target_id'] = $target_id;

        return $this;
    }

    /**
     * Gets target_setting
     *
     * @return \YahooAdsDisplayApi\Client\Model\StatsServiceTargetSetting|null
     */
    public function getTargetSetting()
    {
        return $this->container['target_setting'];
    }

    /**
     * Sets target_setting
     *
     * @param \YahooAdsDisplayApi\Client\Model\StatsServiceTargetSetting|null $target_setting target_setting
     *
     * @return self
     */
    public function setTargetSetting($target_setting)
    {
        $this->container['target_setting'] = $target_setting;

        return $this;
    }

    /**
     * Gets target_type
     *
     * @return \YahooAdsDisplayApi\Client\Model\StatsServiceTargetType|null
     */
    public function getTargetType()
    {
        return $this->container['target_type'];
    }

    /**
     * Sets target_type
     *
     * @param \YahooAdsDisplayApi\Client\Model\StatsServiceTargetType|null $target_type target_type
     *
     * @return self
     */
    public function setTargetType($target_type)
    {
        $this->container['target_type'] = $target_type;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


