<?php
/**
 * DictionaryServiceApiTest
 * PHP version 7.2
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Yahoo!広告 ディスプレイ広告 API リファレンス / Yahoo! JAPAN Ads Display Ads API Reference
 *
 * <div lang=\"ja\">Yahoo!広告 ディスプレイ広告 APIのWebサービスについて説明します。</div> <div lang=\"en\">Display Ads API Web Services supported in Yahoo! JAPAN Ads API.</div> <div><a target=\"_blank\" href=\"https://github.com/yahoojp-marketing/ads-display-api-documents/blob/master/design/v4/Route.yaml\">OpenAPI Specification</a></div> <div lang=\"ja\"><a target=\"_blank\" href=\"https://github.com/yahoojp-marketing/ads-display-api-documents/blob/master/bestpractice/ja\">Best Practice</a></div> <div lang=\"en\"><a target=\"_blank\" href=\"https://github.com/yahoojp-marketing/ads-display-api-documents/blob/master/bestpractice/en\">Best Practice</a></div>
 *
 * The version of the OpenAPI document: v4
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.1.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace OpenAPI\Client\Test\Api;

use \OpenAPI\Client\Configuration;
use \OpenAPI\Client\ApiException;
use \OpenAPI\Client\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * DictionaryServiceApiTest Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class DictionaryServiceApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for dictionaryServiceGetAudienceCategoryPost
     *
     * .
     *
     */
    public function testDictionaryServiceGetAudienceCategoryPost()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for dictionaryServiceGetBusinessCategoryPost
     *
     * .
     *
     */
    public function testDictionaryServiceGetBusinessCategoryPost()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for dictionaryServiceGetDisapprovalReasonPost
     *
     * .
     *
     */
    public function testDictionaryServiceGetDisapprovalReasonPost()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for dictionaryServiceGetFeedItemGoogleProductCategoryPost
     *
     * .
     *
     */
    public function testDictionaryServiceGetFeedItemGoogleProductCategoryPost()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for dictionaryServiceGetGeographicLocationPost
     *
     * .
     *
     */
    public function testDictionaryServiceGetGeographicLocationPost()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for dictionaryServiceGetInterestCategoryPost
     *
     * .
     *
     */
    public function testDictionaryServiceGetInterestCategoryPost()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for dictionaryServiceGetMediaAdFormatPost
     *
     * .
     *
     */
    public function testDictionaryServiceGetMediaAdFormatPost()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for dictionaryServiceGetOsVersionPost
     *
     * .
     *
     */
    public function testDictionaryServiceGetOsVersionPost()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for dictionaryServiceGetSiteCategoryPost
     *
     * .
     *
     */
    public function testDictionaryServiceGetSiteCategoryPost()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for dictionaryServiceGetThirdPartyTrackingDomainPost
     *
     * .
     *
     */
    public function testDictionaryServiceGetThirdPartyTrackingDomainPost()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
